#!/bin/bash
set -e

# Configuration
RESOURCE_GROUP="rg-dev-env"
LOCATION="swedencentral"
VM_NAME="vm-dev"
SSH_KEY_PATH="${HOME}/.ssh/dev_env_key"
SSH_USER="azureuser"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
INFRA_DIR="${SCRIPT_DIR}/../infra"
ENV_FILE="${SCRIPT_DIR}/../.env"

echo "=== Azure Spot VM Deployment ==="

# Check if Azure CLI is installed
if ! command -v az &> /dev/null; then
    echo "Error: Azure CLI is not installed. Install it from https://docs.microsoft.com/en-us/cli/azure/install-azure-cli"
    exit 1
fi

# Check if logged in to Azure
if ! az account show &> /dev/null; then
    echo "Error: Not logged in to Azure. Run 'az login' first."
    exit 1
fi

# Generate SSH key if it doesn't exist
if [ ! -f "${SSH_KEY_PATH}" ]; then
    echo "Generating SSH key at ${SSH_KEY_PATH}..."
    ssh-keygen -t ed25519 -f "${SSH_KEY_PATH}" -N "" -C "dev-env-vm"
    echo "SSH key generated."
fi

# Read SSH public key
SSH_PUBLIC_KEY=$(cat "${SSH_KEY_PATH}.pub")

# Get current public IP for NSG
echo "Getting your public IP..."
MY_IP=$(curl -s ifconfig.me)
echo "Your IP: ${MY_IP}"

# Create resource group if it doesn't exist
echo "Creating resource group ${RESOURCE_GROUP}..."
az group create --name "${RESOURCE_GROUP}" --location "${LOCATION}" --output none

# Deploy infrastructure
echo "Deploying infrastructure..."
az deployment group create \
    --resource-group "${RESOURCE_GROUP}" \
    --template-file "${INFRA_DIR}/main.bicep" \
    --parameters \
        location="swedencentral" \
        namePrefix="dev-env" \
        vmName="${VM_NAME}" \
        vmSize="Standard_D2s_v5" \
        osDiskSizeGB=64 \
        sshPublicKey="${SSH_PUBLIC_KEY}" \
        allowedSshIps="[\"${MY_IP}/32\"]" \
    --output table

# Get public IP
echo ""
echo "=== Deployment Complete ==="
PUBLIC_IP=$(az vm show \
    --resource-group "${RESOURCE_GROUP}" \
    --name "${VM_NAME}" \
    --show-details \
    --query publicIps \
    --output tsv | tr -d '\r')

# Write config to .env file
cat > "${ENV_FILE}" << EOF
# Dev VM Configuration
# Auto-generated by deploy.sh on $(date)

VM_IP=${PUBLIC_IP}
VM_NAME=${VM_NAME}
RESOURCE_GROUP=${RESOURCE_GROUP}
SSH_KEY_PATH=${SSH_KEY_PATH}
SSH_USER=${SSH_USER}
EOF

echo "Config saved to ${ENV_FILE}"
echo ""
echo "Public IP: ${PUBLIC_IP}"
echo "SSH Command: ssh -i ${SSH_KEY_PATH} ${SSH_USER}@${PUBLIC_IP}"
echo ""
echo "Quick connect: ./scripts/ssh-connect.sh"
echo ""
echo "Note: It may take a few minutes for Docker to be installed."
