#!/bin/bash
# Sync 1Password service account token to VM for direct SSH sessions
# This enables secrets via `op` CLI when SSHing directly to the VM (not via DevPod)
#
# Secrets are fetched on-demand from 1Password - they never touch disk as plaintext
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/../.env"
OP_TOKEN_FILE="${HOME}/.config/dev_env/op_token"
OP_SECRETS_SCRIPT="${SCRIPT_DIR}/op-secrets.sh"

# Load VM config
if [ -f "${ENV_FILE}" ]; then
    source "${ENV_FILE}"
else
    echo "Error: Config file not found. Run ./scripts/deploy.sh first."
    exit 1
fi

SSH_KEY_PATH="${SSH_KEY_PATH/#\~/$HOME}"
SSH_OPTS="-o StrictHostKeyChecking=accept-new -o LogLevel=ERROR"

echo "=== Syncing 1Password Configuration to VM ==="

# Check for service account token
if [ ! -f "$OP_TOKEN_FILE" ]; then
    echo ""
    echo "1Password Service Account Token not found at: $OP_TOKEN_FILE"
    echo ""
    echo "To configure:"
    echo "  1. Get token from: 1Password → Settings → Developer → Service Accounts"
    echo "  2. Save it: echo 'your-token' > ${OP_TOKEN_FILE} && chmod 600 ${OP_TOKEN_FILE}"
    echo "  3. Re-run this script"
    exit 1
fi

OP_TOKEN=$(cat "$OP_TOKEN_FILE")

if [ -z "$OP_TOKEN" ]; then
    echo "Error: Token file exists but is empty"
    exit 1
fi

echo "Setting up 1Password on VM..."

# Create remote config directory
ssh -i "${SSH_KEY_PATH}" $SSH_OPTS "${SSH_USER}@${VM_IP}" \
    "mkdir -p ~/.config/dev_env && chmod 700 ~/.config/dev_env"

# Copy the op-secrets.sh helper script
echo "Copying op-secrets.sh helper..."
scp -i "${SSH_KEY_PATH}" $SSH_OPTS \
    "$OP_SECRETS_SCRIPT" "${SSH_USER}@${VM_IP}:~/.config/dev_env/op-secrets.sh"

# Set up the service account token (secure file, never in shell history)
echo "Configuring service account token..."
ssh -i "${SSH_KEY_PATH}" $SSH_OPTS "${SSH_USER}@${VM_IP}" bash -s <<EOF
# Store token securely (600 permissions)
cat > ~/.config/dev_env/op_token << 'TOKENEOF'
${OP_TOKEN}
TOKENEOF
chmod 600 ~/.config/dev_env/op_token

# Create shell initialization snippet
cat > ~/.config/dev_env/init.sh << 'INITEOF'
# 1Password secrets loader (auto-generated by dev_env)
export OP_SERVICE_ACCOUNT_TOKEN="\$(cat ~/.config/dev_env/op_token 2>/dev/null)"
if [ -f ~/.config/dev_env/op-secrets.sh ]; then
    source ~/.config/dev_env/op-secrets.sh
fi
INITEOF
chmod 644 ~/.config/dev_env/init.sh

# Add to .zshrc if not already there
if ! grep -q "dev_env/init.sh" ~/.zshrc 2>/dev/null; then
    echo '' >> ~/.zshrc
    echo '# 1Password secrets (dev_env)' >> ~/.zshrc
    echo '[ -f ~/.config/dev_env/init.sh ] && source ~/.config/dev_env/init.sh' >> ~/.zshrc
fi

# Add to .bashrc if not already there
if ! grep -q "dev_env/init.sh" ~/.bashrc 2>/dev/null; then
    echo '' >> ~/.bashrc
    echo '# 1Password secrets (dev_env)' >> ~/.bashrc
    echo '[ -f ~/.config/dev_env/init.sh ] && source ~/.config/dev_env/init.sh' >> ~/.bashrc
fi
EOF

# Verify 1Password CLI works on VM
echo ""
echo "Verifying 1Password CLI on VM..."
ssh -i "${SSH_KEY_PATH}" $SSH_OPTS "${SSH_USER}@${VM_IP}" bash -s <<EOF
export OP_SERVICE_ACCOUNT_TOKEN="\$(cat ~/.config/dev_env/op_token)"
if command -v op &>/dev/null; then
    if op whoami &>/dev/null; then
        echo "✓ 1Password CLI authenticated successfully"
        echo "  Account: \$(op whoami --format=json 2>/dev/null | jq -r '.email // .url' 2>/dev/null || echo 'service account')"
    else
        echo "✗ 1Password CLI installed but authentication failed"
        echo "  Check your service account token and vault permissions"
    fi
else
    echo "✗ 1Password CLI not installed (waiting for cloud-init?)"
    echo "  Run: sudo apt-get update && sudo apt-get install -y 1password-cli"
fi
EOF

echo ""
echo "=== Sync Complete ==="
echo ""
echo "Secrets are now available via 1Password CLI on the VM."
echo "They are fetched on-demand and never stored as plaintext."
echo ""
echo "To test, SSH to VM and run:"
echo "  op read 'op://DEV_CLI/OpenAI/api_key'"
echo ""
